CREATE TABLE clients(
    id NUMBER GENERATED BY DEFAULT AS identity,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    tel VARCHAR(13) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE livres(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titre VARCHAR(100) NOT NULL,
    auteur VARCHAR(100) NOT NULL,
    publication_date DATE NOT NULL,
    stock NUMBER DEFAULT 0 NOT NULL ,
    PRIMARY KEY (id)
);

CREATE TABLE member_type(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50),
    prix FLOAT,
    nbr_livre_autorise NUMBER
);

CREATE TABLE carte_membre(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    date_creation DATE NOT NULL,
    client_id NUMBER NOT NULL,
    type_id NUMBER NOT NULL,
    etat VARCHAR(20),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE location_livre(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    livre_id NUMBER,
    client_id NUMBER,
    date_sortie DATE,
    date_retour DATE,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (livre_id) REFERENCES livres(id)
);


